name: Website deployment

on:
  release:
      types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.2.2.1/pandoc-2.2.2.1-1-amd64.deb -O /tmp/pandoc.deb
          sudo dpkg -i /tmp/pandoc.deb
          wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz -O /tmp/wkhtml.tar.xz
          sudo tar -xf /tmp/wkhtml.tar.xz --strip-components=1 -C /usr/local

      - name: Run the PDF compilation process
        run: bin/build.sh

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.CI_CD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CI_CD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Trigger S3 deployment
        run: |
          aws s3 sync build s3://wca-documents/ --acl public-read
          # Update version file so the website will update its cache
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          echo "$git_hash" > version
          aws s3 cp version s3://wca-documents/version
          aws cloudfront create-invalidation --distribution-id E31ELE3W069ZX7 --paths "/*" --output text
